#include "../common/schwung_api.h"
#include "../common/warp_core.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <random>
#include <string>
#include <vector>
using namespace warp;
static const host_api_v1_t*g_host=nullptr;static float cf(float x,float a,float b){return std::max(a,std::min(b,x));}static int ci(int x,int a,int b){return std::max(a,std::min(b,x));}
struct Pad{CachedSample s;std::string path;float vol=1,pan=0,tune=0,attack=0,decay=250,chance=100;int choke=0;bool gate=false;};
struct Voice{bool on=false,releasing=false;int pad=0,note=0;const AudioBuffer*b=nullptr;double pos=0,inc=1;float env=1,gl=1,gr=1;};
struct Inst{std::string dir,err,status="Ready";std::array<Pad,16>p;std::array<Voice,64>v;int current=0,poly=16;bool auto_root=true;int default_root=60;bool slice_analyze=true;int slice_count=8;bool pitched_mode=false;bool recording=false;std::vector<int16_t>capture;};
static void upd(Pad&p,LengthAnchor a){p.s.state.anchor=a;reconcile_length(p.s.state,p.s.trimmed_ms(),a);p.s.invalidate();}
static void root(Pad&p){auto q=detect_pitch(trim_audio(p.s.source,p.s.state.trim_start,p.s.state.trim_end));if(q.valid){p.s.state.root_note=q.nearest_midi;p.s.invalidate();}}
static void ensure_pad_cache(Inst*i,int pi,int lo,int hi){if(pi<0||pi>15)return;auto&p=i->p[pi];if(!p.s.state.warp||p.s.source.frames<=0)return;i->status="Rendering pad cache";p.s.prewarm(lo,hi,g_host?g_host->sample_rate:44100);i->status="Ready";}
static void load(Inst*i,int pi,const char*path){if(pi<0||pi>15)return;AudioBuffer a;std::string e;if(!read_wav(path,a,e)){i->err=e;return;}auto& p=i->p[pi];p.path=path;p.s.set_source(std::move(a));if(i->auto_root)root(p);else p.s.state.root_note=i->default_root;upd(p,LengthAnchor::Percent);ensure_pad_cache(i,pi,p.s.state.root_note-12,p.s.state.root_note+12);i->status="Ready";}
static Voice*alloc(Inst*i){for(int k=0;k<i->poly;k++)if(!i->v[k].on)return&i->v[k];return&i->v[0];}
static void kill_choke(Inst*i,int ch){if(!ch)return;for(auto&v:i->v)if(v.on&&i->p[v.pad].choke==ch)v.on=false;}
static void trig(Inst*i,int pi,int pitch_note,int vel){if(pi<0||pi>15)return;auto&p=i->p[pi];if(p.s.source.frames<2)return;static std::mt19937 rng(1);if(std::uniform_real_distribution<float>(0,100)(rng)>p.chance)return;kill_choke(i,p.choke);auto*v=alloc(i);*v=Voice{};v->on=true;v->pad=pi;v->note=pitch_note;float pan=cf(p.pan,-1,1),g=(vel/127.f)*p.vol;v->gl=g*std::sqrt((1-pan)*.5f);v->gr=g*std::sqrt((1+pan)*.5f);v->env=p.attack<=0?1:0;if(p.s.state.warp){v->b=p.s.get_or_render(pitch_note,g_host?g_host->sample_rate:44100);v->inc=1;}else{v->b=&p.s.source;double st=pitch_note-p.s.state.root_note+p.tune;v->inc=std::pow(2.,st/12.)*p.s.source.sample_rate/(g_host?g_host->sample_rate:44100);v->pos=p.s.state.trim_start*std::max(0,p.s.source.frames-1);}}
static void release_note(Inst*i,int note){for(auto&v:i->v)if(v.on&&v.note==note&&i->p[v.pad].gate)v.releasing=true;}
static void slice(Inst*i){auto parent=i->p[i->current];auto t=trim_audio(parent.s.source,parent.s.state.trim_start,parent.s.state.trim_end);if(t.frames<32)return;int count=ci(i->slice_count,2,16);std::filesystem::path d=std::filesystem::path(i->dir)/"slices";std::error_code ec;std::filesystem::create_directories(d,ec);for(int s=0;s<count;s++){int a=int((int64_t)t.frames*s/count),b=int((int64_t)t.frames*(s+1)/count);AudioBuffer q;q.frames=b-a;q.channels=t.channels;q.sample_rate=t.sample_rate;q.data.assign(t.data.begin()+size_t(a)*t.channels,t.data.begin()+size_t(b)*t.channels);int pi=(i->current+s)%16;auto np=parent;np.s=CachedSample{};np.s.state=parent.s.state;np.s.state.trim_start=0;np.s.state.trim_end=1;np.s.set_source(q);np.s.state.grain_ms=parent.s.state.grain_ms;np.s.state.warp=parent.s.state.warp;np.s.state.root_note=parent.s.state.root_note;if(i->slice_analyze)root(np);upd(np,LengthAnchor::Percent);auto path=(d/("slice_"+std::to_string(pi+1)+".wav")).string();std::string e;write_wav16(path,q,e);np.path=path;i->p[pi]=std::move(np);}i->status="Sliced";}
static void record_toggle(Inst*i){if(!i->recording){i->capture.clear();i->recording=true;i->status="Recording pad";}else{i->recording=false;int fr=i->capture.size()/2;if(fr<32)return;AudioBuffer a;a.frames=fr;a.channels=2;a.sample_rate=g_host?g_host->sample_rate:44100;a.data.resize(i->capture.size());for(size_t k=0;k<i->capture.size();k++)a.data[k]=i->capture[k]/32768.f;auto d=std::filesystem::path(i->dir)/"recordings";std::error_code ec;std::filesystem::create_directories(d,ec);auto path=(d/("pad_"+std::to_string(i->current+1)+".wav")).string();std::string e;write_wav16(path,a,e);auto&p=i->p[i->current];p.path=path;p.s.set_source(std::move(a));if(i->auto_root)root(p);else p.s.state.root_note=i->default_root;upd(p,LengthAnchor::Percent);ensure_pad_cache(i,i->current,p.s.state.root_note-12,p.s.state.root_note+12);i->status="Recorded";}}
static void*create(const char*d,const char*){auto*i=new Inst;i->dir=d?d:".";for(auto&p:i->p){p.s.state.warp=true;p.s.state.length_percent=100;p.s.state.grain_ms=45;p.s.state.root_note=60;}return i;}static void destroy(void*p){delete(Inst*)p;}
static bool on(const char*v){return v&&(strcmp(v,"on")==0||strcmp(v,"1")==0||strcmp(v,"true")==0);}static bool padkey(const char*k,int&pi,std::string&f){if(k[0]!='p'||strlen(k)<6)return false;pi=(k[1]-'0')*10+k[2]-'0'-1;if(pi<0||pi>15||k[3]!='_')return false;f=k+4;return true;}
static void setpad(Inst*i,int pi,const std::string&f,const char*v){auto&p=i->p[pi];if(f=="sample_path")load(i,pi,v);else if(f=="vol")p.vol=cf(atof(v),0,2);else if(f=="pan")p.pan=cf(atof(v),-1,1);else if(f=="tune"){p.tune=cf(atof(v),-24,24);p.s.invalidate();}else if(f=="trim_start"){p.s.state.trim_start=cf(atof(v),0,1);upd(p,p.s.state.anchor);}else if(f=="trim_end"){p.s.state.trim_end=cf(atof(v),0,1);upd(p,p.s.state.anchor);}else if(f=="warp"){p.s.state.warp=on(v);p.s.invalidate();}else if(f=="length_pct"){p.s.state.length_percent=cf(atof(v),1,800);upd(p,LengthAnchor::Percent);}else if(f=="length_ms"){p.s.state.length_ms=cf(atof(v),1,600000);upd(p,LengthAnchor::Milliseconds);}else if(f=="grain_ms"){p.s.state.grain_ms=cf(atof(v),5,250);p.s.invalidate();}else if(f=="root_note"){p.s.state.root_note=parse_midi_note(v,p.s.state.root_note);p.s.invalidate();}else if(f=="attack_ms")p.attack=cf(atof(v),0,5000);else if(f=="decay_ms")p.decay=cf(atof(v),0,5000);else if(f=="choke_group")p.choke=ci(atoi(v),0,16);else if(f=="mode")p.gate=!strcmp(v,"gate");else if(f=="chance_pct")p.chance=cf(atof(v),0,100);}
static void setp(void*x,const char*k,const char*v){auto*i=(Inst*)x;if(!i||!k||!v)return;int pi;std::string f;if(padkey(k,pi,f)){setpad(i,pi,f,v);return;}if(!strcmp(k,"current_pad"))i->current=ci(atoi(v)-1,0,15);else if(!strcmp(k,"auto_root"))i->auto_root=on(v);else if(!strcmp(k,"default_root"))i->default_root=parse_midi_note(v,i->default_root);else if(!strcmp(k,"slice_analyze"))i->slice_analyze=on(v);else if(!strcmp(k,"slice_count"))i->slice_count=ci(atoi(v),2,16);else if(!strcmp(k,"slice"))slice(i);else if(!strcmp(k,"pitched_mode")){i->pitched_mode=on(v);if(i->pitched_mode){auto&p=i->p[i->current];ensure_pad_cache(i,i->current,p.s.state.root_note-12,p.s.state.root_note+12);}}else if(!strcmp(k,"polyphony"))i->poly=ci(atoi(v),1,64);else if(!strcmp(k,"record"))record_toggle(i);else if(!strcmp(k,"pad_vol"))setpad(i,i->current,"vol",v);else if(!strcmp(k,"pad_pan"))setpad(i,i->current,"pan",v);else if(!strcmp(k,"pad_tune"))setpad(i,i->current,"tune",v);else if(!strcmp(k,"pad_trim_start"))setpad(i,i->current,"trim_start",v);else if(!strcmp(k,"pad_trim_end"))setpad(i,i->current,"trim_end",v);else if(!strcmp(k,"pad_attack_ms"))setpad(i,i->current,"attack_ms",v);else if(!strcmp(k,"pad_decay_ms"))setpad(i,i->current,"decay_ms",v);else if(!strcmp(k,"pad_choke_group"))setpad(i,i->current,"choke_group",v);else if(!strcmp(k,"pad_mode"))setpad(i,i->current,"mode",v);else if(!strcmp(k,"pad_chance_pct"))setpad(i,i->current,"chance_pct",v);else if(!strcmp(k,"pad_warp"))setpad(i,i->current,"warp",v);else if(!strcmp(k,"pad_length_pct"))setpad(i,i->current,"length_pct",v);else if(!strcmp(k,"pad_length_ms"))setpad(i,i->current,"length_ms",v);else if(!strcmp(k,"pad_grain_ms"))setpad(i,i->current,"grain_ms",v);else if(!strcmp(k,"pad_root_note"))setpad(i,i->current,"root_note",v);}
static int getp(void*x,const char*k,char*b,int n){auto*i=(Inst*)x;if(!i||!k||!b)return-1;auto&p=i->p[i->current];if(!strcmp(k,"current_pad"))return snprintf(b,n,"%d",i->current+1);if(!strcmp(k,"pad_vol"))return snprintf(b,n,"%.3f",p.vol);if(!strcmp(k,"pad_pan"))return snprintf(b,n,"%.3f",p.pan);if(!strcmp(k,"pad_tune"))return snprintf(b,n,"%.3f",p.tune);if(!strcmp(k,"pad_trim_start"))return snprintf(b,n,"%.5f",p.s.state.trim_start);if(!strcmp(k,"pad_trim_end"))return snprintf(b,n,"%.5f",p.s.state.trim_end);if(!strcmp(k,"pad_attack_ms"))return snprintf(b,n,"%.3f",p.attack);if(!strcmp(k,"pad_decay_ms"))return snprintf(b,n,"%.3f",p.decay);if(!strcmp(k,"pad_choke_group"))return snprintf(b,n,"%d",p.choke);if(!strcmp(k,"pad_mode"))return snprintf(b,n,"%s",p.gate?"gate":"oneshot");if(!strcmp(k,"pad_chance_pct"))return snprintf(b,n,"%.3f",p.chance);if(!strcmp(k,"pad_warp"))return snprintf(b,n,"%s",p.s.state.warp?"on":"off");if(!strcmp(k,"pad_length_pct"))return snprintf(b,n,"%.3f",p.s.state.length_percent);if(!strcmp(k,"pad_length_ms"))return snprintf(b,n,"%.3f",p.s.state.length_ms);if(!strcmp(k,"pad_grain_ms"))return snprintf(b,n,"%.3f",p.s.state.grain_ms);if(!strcmp(k,"pad_root_note"))return snprintf(b,n,"%d",p.s.state.root_note);if(!strcmp(k,"pad_root_name"))return snprintf(b,n,"%s",midi_note_name_ableton(p.s.state.root_note).c_str());if(!strcmp(k,"status"))return snprintf(b,n,"%s",i->status.c_str());return-1;}static int err(void*x,char*b,int n){auto*i=(Inst*)x;if(!i||i->err.empty())return 0;return snprintf(b,n,"%s",i->err.c_str());}
static void midi(void*x,const uint8_t*m,int len,int source){auto*i=(Inst*)x;if(!i||!m||len<2)return;int st=m[0]&0xf0,n=m[1],v=len>2?m[2]:0;if(source==0&&n==118&&(st==0x90||st==0xb0)){if(v||st==0x90)record_toggle(i);return;}if(st==0x90&&v){if(i->pitched_mode)trig(i,i->current,n,v);else if(n>=36&&n<=51)trig(i,n-36,i->p[n-36].s.state.root_note,v);}else if(st==0x80||(st==0x90&&!v))release_note(i,n);}
static void render(void*x,int16_t*out,int fr){auto*i=(Inst*)x;if(!i||!out)return;std::fill(out,out+fr*2,0);int sr=g_host?g_host->sample_rate:44100;if(i->recording&&g_host&&g_host->mapped_memory){auto*in=(int16_t*)(g_host->mapped_memory+g_host->audio_in_offset);i->capture.insert(i->capture.end(),in,in+fr*2);}for(auto&v:i->v){if(!v.on||!v.b)continue;auto&p=i->p[v.pad];for(int j=0;j<fr&&v.on;j++){if(v.releasing){v.env-=p.decay<=0?1:1.f/(p.decay*.001f*sr);if(v.env<=0){v.on=false;break;}}else if(v.env<1){v.env+=p.attack<=0?1:1.f/(p.attack*.001f*sr);if(v.env>1)v.env=1;}int q=(int)v.pos;if(q>=v.b->frames-1){v.on=false;break;}double f=v.pos-q;float l,r;if(v.b->channels==1){l=r=float(v.b->data[q]+(v.b->data[q+1]-v.b->data[q])*f);}else{l=float(v.b->data[q*2]+(v.b->data[(q+1)*2]-v.b->data[q*2])*f);r=float(v.b->data[q*2+1]+(v.b->data[(q+1)*2+1]-v.b->data[q*2+1])*f);}int L=out[j*2]+int(l*v.gl*v.env*32767),R=out[j*2+1]+int(r*v.gr*v.env*32767);out[j*2]=(int16_t)ci(L,-32768,32767);out[j*2+1]=(int16_t)ci(R,-32768,32767);v.pos+=v.inc;if(!p.s.state.warp&&v.pos>=p.s.state.trim_end*(p.s.source.frames-1))v.on=false;}}}
static plugin_api_v2_t api{};extern "C" plugin_api_v2_t*move_plugin_init_v2(const host_api_v1_t*h){g_host=h;api.api_version=2;api.create_instance=create;api.destroy_instance=destroy;api.on_midi=midi;api.set_param=setp;api.get_param=getp;api.get_error=err;api.render_block=render;return&api;}
