"""Embed typed sampler pages for Schwung's sound-generator get_param contract."""
import json
from pathlib import Path
from typing import Any

project_root: Path = Path(__file__).resolve().parents[1]
map_parameter_to_range: dict[str, tuple[float, float]] = {
    "trim_start": (0, 1), "trim_end": (0, 1), "attack_ms": (0, 10000),
    "release_ms": (0, 10000), "gain": (0, 2), "transpose": (-48, 48),
    "fine_tune": (-100, 100), "polyphony": (1, 16), "default_root": (0, 127),
    "root_note": (0, 127), "length_pct": (1, 800), "length_ms": (1, 600000),
    "grain_ms": (5, 250), "current_pad": (1, 16), "vol": (0, 2),
    "pan": (-1, 1), "tune": (-24, 24), "decay_ms": (0, 5000),
    "choke_group": (0, 16), "chance_pct": (0, 100), "slice_count": (2, 16),
}
integer_parameters: set[str] = {
    "transpose", "fine_tune", "polyphony", "default_root", "root_note",
    "current_pad", "choke_group", "slice_count",
}
toggle_parameters: set[str] = {"warp", "auto_root", "slice_analyze", "pitched_mode"}
action_parameters: set[str] = {"record", "analyze_root", "rebuild_cache", "slice"}


def descriptor(parameter: str, drums: bool) -> dict[str, Any]:
    """Return an explicit host descriptor for one supported parameter."""
    base_parameter: str = parameter.removeprefix("pad_")
    result: dict[str, Any] = {"key": parameter, "name": base_parameter.replace("_", " ").title()}
    if base_parameter in toggle_parameters:
        result.update(type="enum", options=["off", "on"])
    elif base_parameter == "mode":
        result.update(type="enum", options=["oneshot", "gate"])
    elif base_parameter in action_parameters:
        result.update(type="enum", options=["off", "on"], access="write")
    elif base_parameter == "sample_path":
        result.update(type="string")
    else:
        minimum: float
        maximum: float
        minimum, maximum = map_parameter_to_range[base_parameter]
        if drums and base_parameter == "polyphony":
            maximum = 64
        if drums and base_parameter == "attack_ms":
            maximum = 5000
        result.update(type="int" if base_parameter in integer_parameters else "float", min=minimum, max=maximum)
    return result


def main() -> None:
    """Generate immutable JSON strings so page queries require no file I/O."""
    lines: list[str] = ["// Generated by scripts/generate_ui.py. Do not edit.", "#pragma once"]
    manifest_path: Path
    for manifest_path in sorted((project_root / "modules").glob("*/module.json")):
        manifest: dict[str, Any] = json.loads(manifest_path.read_text())
        module_id: str = manifest["id"]
        drums: bool = module_id in {"warpmrdrums", "warpdrumkit"}
        if not drums:
            continue  # Preserve the existing melodic waveform/file-browser UI.
        hierarchy: dict[str, Any] = manifest["capabilities"]["ui_hierarchy"]
        map_parameter_to_descriptor: dict[str, dict[str, Any]] = {}
        level: dict[str, Any]
        for level in hierarchy["levels"].values():
            parameter: str | dict[str, Any]
            for parameter in level["params"]:
                if isinstance(parameter, str):
                    map_parameter_to_descriptor[parameter] = descriptor(parameter, drums)
            knob: str
            for knob in level.get("knobs", []):
                map_parameter_to_descriptor[knob] = descriptor(knob, drums)
            level["params"] = [descriptor(parameter, drums) if isinstance(parameter, str) else parameter for parameter in level["params"]]
        hierarchy_json: str = json.dumps(hierarchy, separators=(",", ":"))
        params_json: str = json.dumps(list(map_parameter_to_descriptor.values()), separators=(",", ":"))
        lines.extend([
            f'inline constexpr const char *{module_id}_hierarchy = R"UI({hierarchy_json})UI";',
            f'inline constexpr const char *{module_id}_params = R"UI({params_json})UI";',
        ])
    (project_root / "src/common/ui_metadata.h").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
