#include "../common/schwung_api.h"
#include "../common/warp_core.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <memory>
#include <string>
#include <vector>
using namespace warp;

static const host_api_v1_t *g_host=nullptr;
static void logmsg(const std::string&s){if(g_host&&g_host->log)g_host->log(s.c_str());}
static float clampf(float x,float a,float b){return std::max(a,std::min(b,x));}
static int clampi(int x,int a,int b){return std::max(a,std::min(b,x));}

struct Voice { bool on=false; int note=60; const AudioBuffer*buf=nullptr; double pos=0,inc=1; float gain=1, env=0; bool releasing=false; };
struct Inst {
    std::string module_dir,error,sample_path,status="Ready";
    CachedSample sample;
    bool auto_root=true; int default_root=60; int poly=8; float gain=1,attack_ms=5,release_ms=150;
    std::array<Voice,16> voices{};
    bool recording=false; std::vector<int16_t> capture; int max_record_seconds=30;
    bool stock_skin=false;
};

static void update_length(Inst*i,LengthAnchor a){i->sample.state.anchor=a;reconcile_length(i->sample.state,i->sample.trimmed_ms(),a);i->sample.invalidate();}
static void analyse_root(Inst*i){auto t=trim_audio(i->sample.source,i->sample.state.trim_start,i->sample.state.trim_end);auto p=detect_pitch(t);if(p.valid){i->sample.state.root_note=p.nearest_midi;i->status="Root "+midi_note_name_ableton(p.nearest_midi);i->sample.invalidate();}else i->status="Root detection uncertain";}
static void ensure_cache(Inst*i,int lo,int hi){if(!i->sample.state.warp||i->sample.source.frames<=0)return;i->status="Rendering cache";i->sample.prewarm(lo,hi,g_host?g_host->sample_rate:44100);i->status="Ready";}
static void load_path(Inst*i,const char*p){AudioBuffer a;std::string e;if(!read_wav(p,a,e)){i->error=e;return;}i->sample_path=p;i->sample.set_source(std::move(a));if(i->auto_root)analyse_root(i);else{i->sample.state.root_note=i->default_root;i->sample.invalidate();}update_length(i,LengthAnchor::Percent);ensure_cache(i,i->sample.state.root_note-12,i->sample.state.root_note+12);i->status="Ready";i->error.clear();}
static Voice* alloc_voice(Inst*i){for(int k=0;k<i->poly;k++)if(!i->voices[k].on)return &i->voices[k];return &i->voices[0];}
static void note_on(Inst*i,int note,int vel){if(i->sample.source.frames<=0)return;Voice*v=alloc_voice(i);*v=Voice{};v->on=true;v->note=note;v->gain=(vel/127.f)*i->gain;v->env=i->attack_ms<=0?1:0;if(i->sample.state.warp){v->buf=i->sample.get_or_render(note,g_host?g_host->sample_rate:44100);v->inc=1.0;}else{v->buf=&i->sample.source;double semis=note-i->sample.state.root_note+i->sample.transpose+i->sample.fine_cents/100.;v->inc=std::pow(2.,semis/12.)*i->sample.source.sample_rate/(g_host?g_host->sample_rate:44100);v->pos=i->sample.state.trim_start*std::max(0,i->sample.source.frames-1);} }
static void note_off(Inst*i,int note){for(auto&v:i->voices)if(v.on&&v.note==note)v.releasing=true;}
static void record_toggle(Inst*i){if(!i->recording){i->capture.clear();i->capture.reserve(size_t((g_host?g_host->sample_rate:44100))*2*i->max_record_seconds);i->recording=true;i->status="Recording";}else{i->recording=false;int frames=i->capture.size()/2;if(frames<32){i->status="Recording too short";return;}AudioBuffer a;a.frames=frames;a.channels=2;a.sample_rate=g_host?g_host->sample_rate:44100;a.data.resize(i->capture.size());for(size_t k=0;k<i->capture.size();k++)a.data[k]=i->capture[k]/32768.f;std::filesystem::path dir=std::filesystem::path(i->module_dir)/"recordings";std::error_code ec;std::filesystem::create_directories(dir,ec);auto path=(dir/"last_recording.wav").string();std::string err;write_wav16(path,a,err);i->sample_path=path;i->sample.set_source(std::move(a));if(i->auto_root)analyse_root(i);else i->sample.state.root_note=i->default_root;update_length(i,LengthAnchor::Percent);ensure_cache(i,i->sample.state.root_note-12,i->sample.state.root_note+12);i->status="Recorded";}}

static void* create_inst(const char*dir,const char*){auto*i=new Inst;i->module_dir=dir?dir:".";i->stock_skin=(i->module_dir.find("warpmelodic")!=std::string::npos);i->sample.state.warp=true;i->sample.state.length_percent=100;i->sample.state.grain_ms=45;i->sample.state.root_note=60;i->sample.state.anchor=LengthAnchor::Percent;return i;}
static void destroy_inst(void*p){delete (Inst*)p;}
static void midi(void*p,const uint8_t*m,int len,int source){if(!p||!m||len<2)return;auto*i=(Inst*)p;uint8_t st=m[0]&0xF0,d1=m[1],d2=len>2?m[2]:0;if(source==0&&d1==118&&(st==0x90||st==0xB0)){if(d2>0||st==0x90)record_toggle(i);return;}if(st==0x90){if(d2)note_on(i,d1,d2);else note_off(i,d1);}else if(st==0x80)note_off(i,d1);else if(st==0xB0&&(d1==120||d1==123))for(auto&v:i->voices)v.on=false;}
static bool on(const char*v){return v&&(std::strcmp(v,"on")==0||std::strcmp(v,"1")==0||std::strcmp(v,"true")==0);}
static void setp(void*p,const char*k,const char*v){auto*i=(Inst*)p;if(!i||!k||!v)return;
 if(!std::strcmp(k,"sample_path")){load_path(i,v);return;} if(!std::strcmp(k,"warp")){i->sample.state.warp=on(v);i->sample.invalidate();return;} if(!std::strcmp(k,"auto_root")){i->auto_root=on(v);return;} if(!std::strcmp(k,"default_root")){i->default_root=parse_midi_note(v,i->default_root);return;} if(!std::strcmp(k,"root_note")){i->sample.state.root_note=parse_midi_note(v,i->sample.state.root_note);i->sample.invalidate();return;} if(!std::strcmp(k,"analyze_root")){analyse_root(i);return;} if(!std::strcmp(k,"trim_start")){i->sample.state.trim_start=clampf(std::atof(v),0,1);update_length(i,i->sample.state.anchor);return;} if(!std::strcmp(k,"trim_end")){i->sample.state.trim_end=clampf(std::atof(v),0,1);update_length(i,i->sample.state.anchor);return;} if(!std::strcmp(k,"length_pct")){i->sample.state.length_percent=clampf(std::atof(v),1,800);update_length(i,LengthAnchor::Percent);return;} if(!std::strcmp(k,"length_ms")){i->sample.state.length_ms=clampf(std::atof(v),1,600000);update_length(i,LengthAnchor::Milliseconds);return;} if(!std::strcmp(k,"grain_ms")){i->sample.state.grain_ms=clampf(std::atof(v),5,250);i->sample.invalidate();return;} if(!std::strcmp(k,"transpose")){i->sample.transpose=clampi(std::atoi(v),-48,48);i->sample.invalidate();return;} if(!std::strcmp(k,"fine_tune")){i->sample.fine_cents=clampi(std::atoi(v),-100,100);i->sample.invalidate();return;} if(!std::strcmp(k,"polyphony")){i->poly=clampi(std::atoi(v),1,16);return;} if(!std::strcmp(k,"gain")){i->gain=clampf(std::atof(v),0,2);return;} if(!std::strcmp(k,"attack_ms")){i->attack_ms=clampf(std::atof(v),0,10000);return;} if(!std::strcmp(k,"release_ms")){i->release_ms=clampf(std::atof(v),0,10000);return;} if(!std::strcmp(k,"record")){record_toggle(i);return;} if(!std::strcmp(k,"rebuild_cache")){i->sample.invalidate();ensure_cache(i,i->sample.state.root_note-12,i->sample.state.root_note+12);return;}}
static int getp(void*p,const char*k,char*b,int n){auto*i=(Inst*)p;if(!i||!k||!b||n<2)return-1;auto f=[&](const char*fmt,auto x){return std::snprintf(b,n,fmt,x);}; if(!std::strcmp(k,"name"))return std::snprintf(b,n,"%s",i->stock_skin?"Melodic Sampler+":"WarpMrSample");if(!std::strcmp(k,"sample_path"))return std::snprintf(b,n,"%s",i->sample_path.c_str());if(!std::strcmp(k,"warp"))return std::snprintf(b,n,"%s",i->sample.state.warp?"on":"off");if(!std::strcmp(k,"auto_root"))return std::snprintf(b,n,"%s",i->auto_root?"on":"off");if(!std::strcmp(k,"default_root"))return std::snprintf(b,n,"%s",midi_note_name_ableton(i->default_root).c_str());if(!std::strcmp(k,"root_note"))return f("%d",i->sample.state.root_note);if(!std::strcmp(k,"root_name"))return std::snprintf(b,n,"%s",midi_note_name_ableton(i->sample.state.root_note).c_str());if(!std::strcmp(k,"length_pct"))return f("%.3f",i->sample.state.length_percent);if(!std::strcmp(k,"length_ms"))return f("%.3f",i->sample.state.length_ms);if(!std::strcmp(k,"grain_ms"))return f("%.3f",i->sample.state.grain_ms);if(!std::strcmp(k,"trim_start"))return f("%.5f",i->sample.state.trim_start);if(!std::strcmp(k,"trim_end"))return f("%.5f",i->sample.state.trim_end);if(!std::strcmp(k,"status"))return std::snprintf(b,n,"%s",i->status.c_str());if(!std::strcmp(k,"recording"))return std::snprintf(b,n,"%s",i->recording?"on":"off");return-1;}
static int geterr(void*p,char*b,int n){auto*i=(Inst*)p;if(!i||i->error.empty())return 0;return std::snprintf(b,n,"%s",i->error.c_str());}
static void render(void*p,int16_t*out,int frames){auto*i=(Inst*)p;if(!i||!out)return;std::fill(out,out+frames*2,0);if(i->recording&&g_host&&g_host->mapped_memory){auto*in=(int16_t*)(g_host->mapped_memory+g_host->audio_in_offset);int cap=(g_host->sample_rate*i->max_record_seconds)*2;int add=std::min(frames*2,cap-(int)i->capture.size());if(add>0)i->capture.insert(i->capture.end(),in,in+add);}
 int sr=g_host?g_host->sample_rate:44100;for(auto&v:i->voices){if(!v.on||!v.buf||v.buf->frames<2)continue;for(int j=0;j<frames&&v.on;j++){if(v.releasing){float dec=i->release_ms<=0?1:1.f/(i->release_ms*.001f*sr);v.env-=dec;if(v.env<=0){v.on=false;break;}}else if(v.env<1){v.env+=i->attack_ms<=0?1:1.f/(i->attack_ms*.001f*sr);if(v.env>1)v.env=1;}int idx=(int)v.pos;if(idx>=v.buf->frames-1){v.on=false;break;}double frac=v.pos-idx;float l=0,r=0;if(v.buf->channels==1){float a=v.buf->data[idx],bb=v.buf->data[idx+1];l=r=float(a+(bb-a)*frac);}else{for(int c=0;c<2;c++){float a=v.buf->data[size_t(idx)*2+c],bb=v.buf->data[size_t(idx+1)*2+c];float z=float(a+(bb-a)*frac);if(c==0)l=z;else r=z;}}float g=v.gain*v.env;int L=out[j*2]+int(l*g*32767),R=out[j*2+1]+int(r*g*32767);out[j*2]=(int16_t)clampi(L,-32768,32767);out[j*2+1]=(int16_t)clampi(R,-32768,32767);v.pos+=v.inc;if(!i->sample.state.warp&&v.pos>=i->sample.state.trim_end*(i->sample.source.frames-1))v.on=false;}}}
static plugin_api_v2_t api{};
extern "C" plugin_api_v2_t* move_plugin_init_v2(const host_api_v1_t*h){g_host=h;api.api_version=2;api.create_instance=create_inst;api.destroy_instance=destroy_inst;api.on_midi=midi;api.set_param=setp;api.get_param=getp;api.get_error=geterr;api.render_block=render;return &api;}
